language: scala
scala:
   - 2.9.3
   - 2.10.4
   - 2.11.2
env:
   global:
      - secure: "M/HkKG4IjcBvNudCxa4SueYEbl5gguXk7pZwZAEqnTidRRkx4FTDln7C65ADAOP8mVlA4drfleEaQNaTH5LHDA/Gb6cBiaRykf6X9C6XdNJqAG1rJd4KzMfkUbhPY2z2fzVSD44RXN4VQPdiM85L/vlzGKA7OvyKQaHeX4YVnmHpVaNp2IP2HL0hUWPSsGWmVGr8ZyvgDOukzNt3QV7hTKtEh37i2VmSjzaP0KeizLy2UMjL5rVvbir6ZzUNP8+KgpyLDE0/ScrrIbXpKBs94ycP3czN94jGnH8RMNGKGZFtmjjIdpxB+t8FtcBWmcEp1uJt4ll+TylOINrUfQHV6AbhwLR4sFvQpY+w7wuYQA2KEf8d8sucV+W6Eoa0itNXoQtm4busWAspQnOn/3mfuweHz6+BNAnO8EN7NsdPEWWCEg80+WxvlN+CNmnftvkT+m/OhT2GpqbM4CLgK11K6c6FAflypvbNTgLB5w7uyaoinHbTkfSuTZ6DsNduuk7S8KDqXZFrE+5QDYn3iQ2Suk1JVYS6lj8ieyaH4Vpq399M2BpBpTWNKJpa9vzCIcNdTacew8xpVBFo5ZDtBHTxYyKw55dqOVxMXE0+a7V8tOSFQcYzmLibnQDK+xwIg4kk41KmE1S72x5c1gAY9RNYa085yz6z8y0w2KQZ8YSvU3g="
script:
   - sbt ++$TRAVIS_SCALA_VERSION compile
   - sbt ++$TRAVIS_SCALA_VERSION test
   - sbt ++$TRAVIS_SCALA_VERSION dist
after_success:
   - javadoc -sourcepath app/locations/*.java -d doc/ locations
   - ./initiate-publish.sh
   - ./dist-publish.sh