language: scala
scala:
   - 2.9.3
   - 2.10.4
   - 2.11.2
env:
   global:
      - secure: A3F1aaeJVGsoAmeuhQofuXCXBJdM0iIBCJY8tPvdo6hnQQUWZW8AmQVCk3b9SUz0alB7Vwr/5nUfHmvjpa6bp5R//svMyfI7k3PoNCI5zZd3qWZ5EXKGZ6/GTCNl54lutp07njKQvQlTy+cWTm84h/bZXqcLXpGSOpM0jMwZow4JKekuq/oDWmQ7WtgvFPTh+wKX7e7Ay0fTCIIZEiX8XRLGCNmZDkw8gfBs0NmuYutM+Q9xaIKcfD8YhBJX3k7PAkmwc07nU7k8DQj+lamOitWjpAGDvWVbEthLzE24l/tR0h/CsLQwr99qM+hUxVL50LI5NjRzZpY6tFnEc73Bv69lp7viITlIo0ob7VKfkZcxtByz7m7Zhw4nwboABtgJQlztJ57Gk9o/3qcuxh/PlXHBaqXWrL4bdCFvS3tx4bh34+pYcmW2EELOfsCNfvpd5H9gr05UbhiBwObVY/DPDjYzBNGJUZAiMOkeDfwPzUOugZ3JTvQyYgaBPnrkkIkK+N1WL+1G3O49QKPqYv0nCSXHrjr30ZnxJPPpr+gVdtR7NzaaOKTjK+UfxuDtS5B8Obo4YYea1r2E1xT24amis94BB9LxoBy1rfxNEs//CYga4FEL4/g5dDBIpfsYrKtzDZDQNsclS7Uf/L//8tONqkJmVuDeifba956p4Esw1Vc=
      - GH_TOKEN=022889ebfd39c06854645c7dfc914e67661385cd
script:
   - sbt ++$TRAVIS_SCALA_VERSION compile
   - sbt ++$TRAVIS_SCALA_VERSION test
after_success:
   - javadoc -sourcepath app/locations/*.java -d doc/ locations
   - ./initiate-publish.sh